#!/usr/bin/env bash

# Builds the version of the game at HEAD then attaches the size to the commit
# as a git note.

set -euo pipefail
commit=$(git rev-parse HEAD)
tmp=$(mktemp -d)

git archive "$commit" | tar -x -C "$tmp"
ln -s "$PWD/node_modules" "$tmp/node_modules"

pushd "$tmp"
make
size=$(wc -c < dist.zip | xargs)
popd

git notes add -fm "size: $size" "$commit"
rm -rf "$tmp"
