// 🚀 Generated by the 'Export JavaScript.lua' Aseprite script!
// https://github.com/danprince/aseprite-config

/**
 * @typedef {"#000000" | "#0c0c0c" | "#ffffff" | "#4c1c1c" | "#ac3232" | "#b34f44" | "#663931" | "#3c221d" | "#6c3a22" | "#8f563b" | "#382b21" | "#eec39a" | "#d9a066" | "#bfad9b" | "#dbcdbf" | "#f3b35d" | "#543f17" | "#97690c" | "#876727" | "#ffc44d" | "#c79b0d" | "#f3ecd4" | "#5c7446" | "#40582b" | "#133024" | "#37946e" | "#111e2c" | "#232d38" | "#162c50" | "#274474" | "#265197" | "#5d84c3" | "#5b8ee1" | "#93b3e7" | "#2f4c93" | "#121220" | "#d95763"} PaletteColor
 * The colors from the sprite's palette.
 *
 * @typedef {object} Sprite An Aseprite slice.
 * @prop {number} x The x coordinate of the top left of the sprite.
 * @prop {number} y The y coordinate of the top left of the sprite.
 * @prop {number} w The width of the sprite in pixels.
 * @prop {number} h The height of the sprite in pixels.
 * @prop {{ x: number, y: number }} [pivot] The coordinates of the sprite's pivot point.
 * @prop {{ x: number, y: number, w: number, h: number }} [center] The central rectangle of the 9-slice.
 * @prop {string} [data] User-data for the sprite.
 *
 * @typedef {Sprite & { center: { x: number, y: number, w: number, h: number } }} NineSliceSprite
 * @typedef {Sprite & { pivot: { x: number, y: number } }} PivotSprite
 */
export const spritesheet = {
  "btn": { center: { h: 8, w: 1, x: 5, y: 2, }, h: 12, w: 11, x: 0, y: 42, },
  "btn_active": { center: { h: 8, w: 1, x: 5, y: 2, }, h: 12, w: 11, x: 11, y: 42, },
  "card_slot": { h: 18, w: 18, x: 54, y: 0, },
  "cards": { h: 54, w: 72, x: 54, y: 0, },
  "font": { h: 30, w: 48, x: 0, y: 0, },
  "icon_heart": { h: 7, w: 7, x: 22, y: 42, },
  "particles": { h: 5, w: 20, x: 22, y: 49, },
  "tooltip": { center: { h: 1, w: 1, x: 1, y: 1, }, h: 3, w: 3, x: 29, y: 42, },
};
