// 🚀 Generated by the 'Export JavaScript.lua' Aseprite script!
// https://github.com/danprince/aseprite-config

/**
 * @typedef {"#000000" | "#202020" | "#404040" | "#606060" | "#808080" | "#a0a0a0" | "#c0c0c0" | "#e0e0e0" | "#2c1414" | "#4c1c1c" | "#663931" | "#8f563b" | "#d9a066" | "#f3ecd4" | "#3c221d" | "#121220" | "#111e2c" | "#133024" | "#232d38" | "#543f17" | "#40582b" | "#162c50" | "#274474" | "#5c7446" | "#ac3232" | "#97690c" | "#876727" | "#b34f44" | "#d95763" | "#37946e" | "#c79b0d" | "#f3b35d" | "#ffc44d" | "#2f4c93" | "#265197" | "#5d84c3" | "#5b8ee1" | "#bfad9b" | "#eec39a" | "#dbcdbf" | "#93b3e7" | "#ffffff" | "#da6d2a" | "#632a08" | "#12251d" | "#29134e" | "#442988" | "#7d42bd"} PaletteColor
 * The colors from the sprite's palette.
 *
 * @typedef {object} Sprite An Aseprite slice.
 * @prop {number} x The x coordinate of the top left of the sprite.
 * @prop {number} y The y coordinate of the top left of the sprite.
 * @prop {number} w The width of the sprite in pixels.
 * @prop {number} h The height of the sprite in pixels.
 * @prop {{ x: number, y: number }} [pivot] The coordinates of the sprite's pivot point.
 * @prop {{ x: number, y: number, w: number, h: number }} [center] The central rectangle of the 9-slice.
 * @prop {string} [data] User-data for the sprite.
 *
 * @typedef {Sprite & { center: { x: number, y: number, w: number, h: number } }} NineSliceSprite
 * @typedef {Sprite & { pivot: { x: number, y: number } }} PivotSprite
 */
export const spritesheet = {
  "btn": { center: { h: 8, w: 1, x: 5, y: 2, }, h: 12, w: 11, x: 80, y: 42, },
  "btn_active": { center: { h: 8, w: 1, x: 5, y: 2, }, h: 12, w: 11, x: 80, y: 42, },
  "card": { h: 18, w: 18, x: 62, y: 36, },
  "card_slot": { h: 18, w: 18, x: 8, y: 0, },
  "cards": { h: 54, w: 72, x: 8, y: 0, },
  "cursors": { h: 10, pivot: { x: 3, y: 1, }, w: 37, x: 91, y: 44, },
  "font": { h: 30, pivot: { x: 0, y: 0, }, w: 48, x: 80, y: 0, },
  "frame": { center: { h: 2, w: 2, x: 6, y: 6, }, h: 14, w: 14, x: 94, y: 30, },
  "particle_1": { h: 3, w: 3, x: 80, y: 30, },
  "particle_2": { h: 4, w: 4, x: 83, y: 30, },
  "particle_bone": { h: 7, w: 7, x: 87, y: 30, },
  "swaps": { h: 19, w: 8, x: 0, y: 0, },
};
